Title: Dr Doe's Chemistry Quiz
Library: arcade
Developer: alfa995
Publisher: Newgrounds
Play Mode: Single Player
Release Date: "2019"
Languages: en
Tags: 3D; Unity WebGL; Anthro; Nudity
Tag Categories: default; default; default; default
Source: https://www.newgrounds.com/portal/view/724772
Primary Platform: HTML5
Platforms: HTML5
Status: Playable
Application Path: FPSoftware\fpnavigator-portable\FPNavigator.exe
Launch Command: http://www.newgrounds.com/portal/view/724772
Original Description: >-
  UPDATE Jan 18 2019:


  -Adjusted difficulty. Easier questions and 30 seconds for each instead of 10.
  The original can still be played as a Hard mode from the main menu, but
  there's no extra rewards, it's just for the challenge.


  -Reduced the intro dialogue when you restart the quiz.


  (Oh and another minor update, sped up the question typing and fixed a bug with
  the dialogue)

  --


  The adorable science deer Dr. Doe is here to test your knowledge of chemistry!
  Answer correctly, she strips. Answer all perfectly and.. well you can imagine
  what your reward will be!


  I made this game to celebrate a milestone on Patreon
  https://www.patreon.com/alfa995 so thanks to everyone who made this possible!


  This is my first actual game (that's not just an interactive animation) so
  it's fairly simple and there might be some bugs here and there, but it was a
  great learning experience and hopefully I'll be able to create better ones in
  the future~
Curation Notes: ""
UUID: 759cb47b-fb0f-4269-a76e-382fd11d7304
Group: ""
Additional Applications: {}
